import { normalizeWhatsAppNumber, whatsappIdFromNumber } from "@/lib/whatsapp/core";
import { enqueueWhatsAppNotifications, sendWhatsAppGreeting } from "@/server/services/whatsapp";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { requireCareContext } from "@/server/auth/require-care-context";
import { z } from "zod";

const schema = z.object({ phone: z.string().min(8).max(24) });
export async function GET() { try { const context = await requireCareContext(); if (context.isDemo) return Response.json({ connected: false, demo: true }); const supabase = await createSupabaseServerClient(); const { data } = await supabase.from("whatsapp_connections").select("phone_e164,status,connected_at").eq("user_id", context.userId).maybeSingle(); return Response.json({ connected: data?.status === "connected", connection: data ?? null }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Unable to load WhatsApp." }, { status: 500 }); } }
export async function POST(request: Request) { const input = schema.safeParse(await request.json()); if (!input.success) return Response.json({ error: "A phone number is required." }, { status: 400 }); try { const context = await requireCareContext(); if (context.isDemo) return Response.json({ error: "Use configured mode for the real WhatsApp test-number demo." }, { status: 400 }); const phone = normalizeWhatsAppNumber(input.data.phone); if (process.env.WHATSAPP_DEMO_RECIPIENT && phone !== normalizeWhatsAppNumber(process.env.WHATSAPP_DEMO_RECIPIENT)) return Response.json({ error: "This number is not the configured Meta test recipient." }, { status: 400 }); const messageId = await sendWhatsAppGreeting(phone); const supabase = await createSupabaseServerClient(); const { data: connection, error } = await supabase.from("whatsapp_connections").upsert({ user_id: context.userId, family_id: context.familyId, phone_e164: phone, wa_id: whatsappIdFromNumber(phone), status: "connected", greeting_message_id: messageId, connected_at: new Date().toISOString() }, { onConflict: "user_id" }).select("id").single(); if (error || !connection) throw error ?? new Error("WhatsApp connection was not saved."); await enqueueWhatsAppNotifications(connection.id, context.familyId); return Response.json({ connected: true, messageId }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Unable to connect WhatsApp." }, { status: 500 }); } }
export async function DELETE() { try { const context = await requireCareContext(); if (context.isDemo) return Response.json({ connected: false }); const supabase = await createSupabaseServerClient(); const { data: connection } = await supabase.from("whatsapp_connections").select("id").eq("user_id", context.userId).maybeSingle(); if (connection) { await supabase.from("whatsapp_dose_notifications").update({ status: "cancelled" }).eq("connection_id", connection.id).in("status", ["pending", "processing"]); await supabase.from("whatsapp_connections").delete().eq("id", connection.id); } return Response.json({ connected: false }); } catch (error) { return Response.json({ error: error instanceof Error ? error.message : "Unable to disconnect WhatsApp." }, { status: 500 }); } }
